version: '3.8'

services:
  crypto-news-bot:
    build: .
    container_name: crypto_news_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  crypto-bot-network:
    driver: bridge

volumes:
  logs: 