[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
TELEGRAM_BOT_TOKEN = ""
GEMINI_API_KEY = ""
ADMIN_USER_IDS = "" 